graphicus-02: src/graphicus-02.cpp  -o graphicus-02 graphicus-02.cpp *.o

tests.o: src/tests.cpp includes/tests.h canevas.o
	g++ tests.cpp -g -c

canevas.o: src/canevas.cpp includes/canevas.h couche.o
	g++ canevas.cpp -g -c

couche.o: src/couche.cpp includes/couche.h forme.o
	g++ couche.cpp -g -c

forme.o: src/forme.cpp includes/forme.h includes/coordonnee.h
	g++ forme.cpp -g -c

clean:
	rm -f *.o

